language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
compiler: gcc
install: true
dist: trusty
sudo: required
before_install:
    - git clone https://github.com/RRZE-HPC/likwid.git
    - cd likwid
    - make && sudo make install
    - cd ..
install:
    - python setup.py build_ext -I /usr/local/include/ -L /usr/local/lib/ -R /usr/local/lib/
    - python setup.py install
before_script:
    - sudo modprobe msr
script:
    - python -c "import pylikwid"
    - ./testtopo.py
    - ./testpin.py
    - ./testaffinity.py
# testmarker.py and testlib.py cannot be used on TravisCI

## for future reference:
deploy:
  provider: pypi
  user: travis.rrze-hpc
  password:
    secure: "NcaLnnOEEQ/hjoSX1x+a2teU+3VafD/GOSug43+wsJSdbpxoK3qwzGdpLHOU1mX3npCfdAmvXdRMNhqCSHKRWgiN8Ir5Rp7kVWBgtmkPm7PfoL36/RjeABUJHZzrpIhH5GU5SrKk+xwGMrLf4aMcLsVVV61jqjC3gh7NpCw8GfkTBwKbA8Ul0YaSPPoWsr6g8DiAnEqlCJvNSVOXeNglZ4EEoUXGruqWvkEINOEMAbf4rODL4SgL2tgxcz9VL1CSj+BprkwYv+diGeq/9VbrtsOsNSBr3+12KccnCXVUFu1zRrCzFwOnHr6QXnJCfkSRpd5Bmj12xIHLZifMEHIHRknSfRXbgO2IeaWNyUYQras/iRmkphC01EgOMyvukB8Udilk9hQnj3h41wnd991fO7Z+cKzL2mr1ZGOajHvneBPn9Pa/RnrX9DL22HcwuGrKtWqlTq9MkBpMIWvpjaEI+BDZS1YIXNyKsaKdYYsK7cGYO4uNUDoJF/asAB+vFuAKjqD6MTToPn0X9v0wvdYVnCv88oHSgfgj6ZBy/Utppx1AoP380huygvdUHei2nc6357PvHfGWbSeoUGvxduloMoeXqggR1XF1mgbye1ZU1bXC/9mjkrBQ/XUcK0ZUnIM9rCn7tOfuzkkMjGCpn00F6H0t2COzNmsc/qshGKLd8+k="
  distributions: "sdist"
  on:
    repo: RRZE-HPC/pylikwid
